"""Compatibility helpers for corpus abbreviation dictionaries.

The public functions in this module are kept for older clustering and web
paths.  Internally they delegate to the conservative keyword-extraction
parenthetical evidence extractor so all SciScape surfaces use the same
abbreviation rules.
"""

from __future__ import annotations

import logging
import re
from typing import Dict, List, Sequence

import pandas as pd
import polars as pl

from sciscape.keyword_extraction.abbreviations import (
    build_abbreviation_lookup,
    extract_parenthetical_abbreviations,
)

log = logging.getLogger(__name__)


def extract_abbreviations(
    abstracts: pl.DataFrame | Sequence[str],
    *,
    min_count: int = 2,
    title_col: str = "title",
    abstract_col: str = "abstract",
) -> Dict[str, str]:
    """Extract abbreviation → full name mapping from abstracts.

    Parameters
    ----------
    abstracts : pl.DataFrame or list of str
        If DataFrame, uses title + abstract columns.
    min_count : int
        Minimum occurrences to keep (filters noise).

    Returns
    -------
    dict
        {abbreviation: canonical_full_name}.  Abbreviations are normalized to
        lower-case to match keyword labels generated by the clustering path.
    """
    if isinstance(abstracts, pl.DataFrame):
        docs = pd.DataFrame(abstracts.to_dicts())
    else:
        texts = list(abstracts)
        docs = pd.DataFrame(
            {
                "uid": [f"doc_{i}" for i in range(len(texts))],
                title_col: [""] * len(texts),
                abstract_col: texts,
            }
        )

    if "uid" not in docs.columns:
        docs = docs.copy()
        docs["uid"] = [f"doc_{i}" for i in range(len(docs))]
    if title_col not in docs.columns:
        docs = docs.copy()
        docs[title_col] = ""
    if abstract_col not in docs.columns:
        docs = docs.copy()
        docs[abstract_col] = ""

    evidence = extract_parenthetical_abbreviations(
        docs,
        uid_col="uid",
        cluster_col=None,
        title_col=title_col,
        abstract_col=abstract_col,
    )
    lookup = build_abbreviation_lookup(
        evidence,
        min_support_docs=min_count,
        min_cluster_support_docs=min_count,
    )
    result = {
        short: str(entry.get("long_form", ""))
        for short, entry in lookup.get("global", {}).items()
        if entry.get("usable") and entry.get("long_form")
    }

    log.info(
        "Extracted %d abbreviations from %d documents (min_count=%d)",
        len(result),
        len(docs),
        min_count,
    )
    return result


def abbreviation_table(abbr_dict: Dict[str, str]) -> pl.DataFrame:
    """Convert abbreviation dict to DataFrame."""
    return pl.DataFrame({
        "abbreviation": list(abbr_dict.keys()),
        "full_name": list(abbr_dict.values()),
    }).sort("abbreviation")


def expand_labels_with_abbreviations(
    labels: List[str],
    abbr_dict: Dict[str, str],
    *,
    mode: str = "append",
) -> List[str]:
    """Expand abbreviations in cluster labels.

    Parameters
    ----------
    mode : str
        "append": "DFT analysis" → "DFT (density functional theory) analysis"
        "replace": "DFT analysis" → "density functional theory analysis"
        "keep": no change, just for lookup
    """
    result = []
    for label in labels:
        new_label = label
        for abbr, full in abbr_dict.items():
            # Only expand if abbreviation appears as whole word
            pattern = r'\b' + re.escape(abbr) + r'\b'
            if re.search(pattern, new_label, flags=re.IGNORECASE):
                if mode == "append":
                    new_label = re.sub(
                        pattern,
                        lambda match: f"{match.group(0)} ({full})",
                        new_label,
                        count=1,
                        flags=re.IGNORECASE,
                    )
                elif mode == "replace":
                    new_label = re.sub(pattern, full, new_label, count=1, flags=re.IGNORECASE)
        result.append(new_label)
    return result


__all__ = [
    "extract_abbreviations",
    "abbreviation_table",
    "expand_labels_with_abbreviations",
]
